import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { buildGeneratedFiles, loadAdrs } from "../src/regenerator.ts";
import { TEST_CONFIG } from "./test-helpers.ts";

let tmp: string;

beforeEach(() => {
  tmp = mkdtempSync(join(tmpdir(), "adr-regenerator-"));
});

afterEach(() => {
  rmSync(tmp, { recursive: true, force: true });
});

function writeAdr(file: string, fm: string, heading: string): void {
  writeFileSync(join(tmp, file), `---\n${fm}\n---\n\n# ${heading}\n\nbody\n`);
}

function seed(): void {
  writeAdr(
    "20260101-01-a.md",
    `id: ADR-20260101-01
title: Active Core
status: accepted
date: 2026-01-01
topic: core-concepts`,
    "ADR-20260101-01: Active Core",
  );
  writeAdr(
    "20260101-02-b.md",
    `id: ADR-20260101-02
title: Old
status: superseded
date: 2026-01-01
topic: parser
superseded_by: ADR-20260101-03`,
    "ADR-20260101-02: Old",
  );
  writeAdr(
    "20260101-03-c.md",
    `id: ADR-20260101-03
title: New Parser
status: accepted
date: 2026-01-01
topic: parser
supersedes:
  - ADR-20260101-02`,
    "ADR-20260101-03: New Parser",
  );
}

describe("buildGeneratedFiles", () => {
  it("produces effective.md, graph.md, and one graph/<topic>.md per topic", () => {
    seed();
    const files = buildGeneratedFiles(loadAdrs(tmp, TEST_CONFIG), TEST_CONFIG);
    const paths = files.map((f) => f.relativePath).sort();
    expect(paths).toContain("effective.md");
    expect(paths).toContain("graph.md");
    expect(paths).toContain("graph/core-concepts.md");
    expect(paths).toContain("graph/parser.md");
  });

  it("effective.md excludes superseded ADRs and groups by topic", () => {
    seed();
    const files = buildGeneratedFiles(loadAdrs(tmp, TEST_CONFIG), TEST_CONFIG);
    const eff = files.find((f) => f.relativePath === "effective.md");
    expect(eff).toBeDefined();
    const body = eff!.contents;
    // Topic headings present
    expect(body).toContain("## core-concepts");
    expect(body).toContain("## parser");
    // Accepted ADRs listed
    expect(body).toContain("ADR-20260101-01");
    expect(body).toContain("ADR-20260101-03");
    // Superseded ADR not listed (body references use ADR id followed by a close-bracket / em-dash)
    expect(body).not.toContain("ADR-20260101-02](");
  });

  it("header says what the file is without counting the ADR set", () => {
    // No aggregate count in the generated output. A count is a property of the
    // whole set, so two PRs that each regenerate against their own base produce
    // headers that are individually right and wrong once merged — git sees no
    // conflict, and the drift only surfaces on the default branch afterwards.
    // Per-ADR rows do not have this problem, so nothing global is written.
    seed();
    const files = buildGeneratedFiles(loadAdrs(tmp, TEST_CONFIG), TEST_CONFIG);
    const eff = files.find((f) => f.relativePath === "effective.md")!;
    expect(eff.contents).toContain("Auto-generated by");
    expect(eff.contents).not.toMatch(/\d+ of \d+ ADRs/);
  });

  it("the overview and its per-topic links carry no counts either", () => {
    seed();
    const files = buildGeneratedFiles(loadAdrs(tmp, TEST_CONFIG), TEST_CONFIG);
    const graph = files.find((f) => f.relativePath === "graph.md")!;
    expect(graph.contents).not.toMatch(/\d+ ADRs across \d+ topics/);
    expect(graph.contents).not.toMatch(/\]\([^)]*\.md\) — \d+ ADRs/);
    // The links themselves stay — only the counts go.
    expect(graph.contents).toMatch(/## Per-topic detail/);
  });

  it("produces deterministic output for the same input", () => {
    seed();
    const first = buildGeneratedFiles(loadAdrs(tmp, TEST_CONFIG), TEST_CONFIG);
    const second = buildGeneratedFiles(loadAdrs(tmp, TEST_CONFIG), TEST_CONFIG);
    expect(first).toEqual(second);
  });
});
